version: "3.0"

services:
  # security within docker can't be verified due to https://stackoverflow.com/questions/70697745/keycloak-token-verification-fails-when-the-backend-is-running-in-a-docker-contai/70708121#70708121
  storage-service-app:
    image: storage-service-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storage-service-app-microservices_course
    environment:
      SPRING_CLOUD_CONFIG_URI: ${SPRING_CLOUD_CONFIG_URI}
    ports:
      - "8085:8085"
    depends_on:
      - postgres
    networks:
      - service-configuration_default
      - service-registry_default
      - postgres
      - resource-service_elasticsearch
      - resource-service_keycloack

  postgres:
    container_name: postgres_storage_service_microservices_course
    image: postgres:11
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5434:5432'
    networks:
      - postgres

networks:
  postgres:
  service-registry_default:
    external: true
  service-configuration_default:
    external: true
  resource-service_elasticsearch:
    external: true
  resource-service_keycloack:
    external: true
